# Generated by Django 4.0.3 on 2022-04-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinkhao', '0004_restaurantlocationsanddays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocations',
            name='days',
        ),
        migrations.DeleteModel(
            name='RestaurantLocationsAndDays',
        ),
    ]
