# Generated by Django 4.0.3 on 2022-04-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinkhao', '0005_remove_restaurantlocations_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantLocationsAndDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kinkhao.days')),
            ],
        ),
        migrations.AddField(
            model_name='restaurantlocations',
            name='days',
            field=models.ManyToManyField(through='kinkhao.RestaurantLocationsAndDays', to='kinkhao.days'),
        ),
        migrations.AddField(
            model_name='restaurantlocationsanddays',
            name='restaurantLocations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinkhao.restaurantlocations'),
        ),
    ]
