# Generated by Django 4.0.3 on 2022-04-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinkhao', '0006_restaurantlocationsanddays_restaurantlocations_days_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='restaurantlocationsanddays',
            constraint=models.UniqueConstraint(fields=('restaurantLocations', 'days'), name='Unique_restaurantLocation_on_day'),
        ),
    ]
