# Generated by Django 4.0.3 on 2022-04-18 21:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinkhao', '0007_restaurantlocationsanddays_unique_restaurantlocation_on_day'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookings1',
            name='unique_table_location_timeSlot',
        ),
        migrations.AddField(
            model_name='bookings1',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 19)),
        ),
        migrations.AddField(
            model_name='bookings1',
            name='day',
            field=models.ForeignKey(default='Saturday', on_delete=django.db.models.deletion.PROTECT, to='kinkhao.days', to_field='day'),
        ),
        migrations.AddConstraint(
            model_name='bookings1',
            constraint=models.UniqueConstraint(fields=('the_table', 'time_slot', 'date'), name='unique_table_location_timeSlot_date'),
        ),
    ]
