# Generated by Django 4.0.3 on 2022-05-04 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinkhao', '0008_remove_bookings1_unique_table_location_timeslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings1',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 4)),
        ),
    ]
