# Generated by Django 4.0.3 on 2022-05-06 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinkhao', '0009_alter_bookings1_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings1',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 6)),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealName',
            field=models.CharField(max_length=30),
        ),
    ]
