# Generated by Django 4.0.3 on 2022-05-09 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinkhao', '0010_alter_bookings1_date_alter_meal_mealname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings1',
            name='day',
        ),
        migrations.RemoveField(
            model_name='restaurantlocations',
            name='days',
        ),
        migrations.AlterField(
            model_name='bookings1',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 9)),
        ),
    ]
