# Generated by Django 4.0.3 on 2022-06-06 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinkhao', '0011_remove_bookings1_day_remove_restaurantlocations_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings1',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 6)),
        ),
    ]
